---
- name: install Grafana & InfluxDB CentOS and Ubuntu
  hosts: monitor
  become: yes
  tasks:
    - block:
        - name: Install Tools 1
          apt:
            name: adduser
            state: present
        - name: Install Tools 2
          apt:
            name: libfontconfig1
            state: present
        - name: Install a .deb package from the internet
          apt:
            deb: https://dl.grafana.com/oss/release/grafana_7.5.4_amd64.deb
        - name: Start Grafana
          service:
            name: grafana-server
            state: started
        - name: Enable Grafana
          service:
            name: grafana-server
            enabled: yes
        - name: Install InfluxDB
          apt:
            deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.5_amd64.deb
        - name: Start Influx
          service:
            name: influxdb
            state: started
            enabled: yes
      when: ansible_distribution == "Ubuntu"
