---
- name: install Grafana & InfluxDB CentOS and Ubuntu
  hosts: monitor
  become: yes
  tasks:
    - block:
        - name: Installing Required Tools 1
          apt:
            name: adduser
            state: present
        - name: Installing Required Tools 2
          apt:
            name: libfontconfig1
            state: present
        - name: Install Grafana .deb package from the grafana public repository
          apt:
            deb: https://dl.grafana.com/oss/release/grafana_7.5.4_amd64.deb
        - name: Start Grafana
          service:
            name: grafana-server
            state: started
        - name: Enable Grafana
          service:
            name: grafana-server
            enabled: yes
        - name: Install InfluxDB .deb package from the influxdb public repository
          apt:
            deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.5_amd64.deb
        - name: Start Influxdb
          service:
            name: influxdb
            state: started
            enabled: yes
        - name: Setting up InfluxDB Config 01 - Setup DB Name
          shell: curl "http://localhost:8086/query" --data-urlencode "q=CREATE DATABASE "{{ db_name }}""
        - name: Setting up InfluxDB Config 02 - Setup DB User
          shell: curl "http://localhost:8086/query" --data-urlencode "q=CREATE USER {{ db_admin_username }} WITH PASSWORD '{{ db_admin_password }}' WITH ALL PRIVILEGES"
        - name: Setting up InfluxDB Config 03 - Setup DB User RBAC
          shell: curl "http://localhost:8086/query" --data-urlencode "q=GRANT ALL PRIVILEGES TO "{{ db_admin_username }}""
        - name: Setting up InfluxDB Config 04 - Setup Config's auth-enabled
          shell: sed -i "s/# auth-enabled = false/auth-enabled = true/g" /etc/influxdb/influxdb.conf
        - name: Update apt-get for installing ansible
          apt:
            update_cache: yes
        - name: Setup for for installing ansible
          apt:
            name: software-properties-common
        - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
          ansible.builtin.apt_repository:
            repo: ppa:ansible/ansible
        - name: Install Ansible
          apt:
            name: ansible
        - name: mkdir telegraf workspace - Setup for deploying telegraf agent to target
          shell: mkdir /tmp/telegraf
        - name: Copy telegraf workspace - Setup for deploying telegraf agent to target
          copy:
            src: ../telegraf/
            dest: /tmp/telegraf/
      when: ansible_distribution == "Ubuntu"