---
- name: install Grafana & InfluxDB CentOS and Ubuntu
  hosts: monitor
  become: yes
  tasks:
    - block:
        - name: Install Tools 1
          apt:
            name: adduser
            state: present
        - name: Install Tools 2
          apt:
            name: libfontconfig1
            state: present
        - name: Install a .deb package from the internet
          apt:
            deb: https://dl.grafana.com/oss/release/grafana_7.5.4_amd64.deb
        - name: Start Grafana
          service:
            name: grafana-server
            state: started
        - name: Enable Grafana
          service:
            name: grafana-server
            enabled: yes
        - name: Install InfluxDB
          apt:
            deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.5_amd64.deb
        - name: Start Influx
          service:
            name: influxdb
            state: started
            enabled: yes
        - name:
          shell: curl "http://localhost:8086/query" --data-urlencode "q=CREATE DATABASE "<DBNAME>""
        - name:
          shell: curl "http://localhost:8086/query" --data-urlencode "q=CREATE USER <USERNAME> WITH PASSWORD '<PASSWORD>' WITH ALL PRIVILEGES"
        - name:
          shell: curl "http://localhost:8086/query" --data-urlencode "q=GRANT ALL PRIVILEGES TO "<USERNAME>""
        - name: Set auth-enabled
          shell: sed -i "s/# auth-enabled = false/auth-enabled = true/g" /etc/influxdb/influxdb.conf
        - name: Update apt-get
          apt:
            update_cache: yes
        - name: 
          apt:
            name: software-properties-common
        - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
          ansible.builtin.apt_repository:
            repo: ppa:ansible/ansible
        - name: Install ansible
          apt:
            name: ansible
        - name: mkdir telegraf workspace
          shell: mkdir /tmp/telegraf
        - name: Copy telegraf workspace
          copy:
            src: ../telegraf/
            dest: /tmp/telegraf/
      when: ansible_distribution == "Ubuntu"