---
- name: Install Telegraf CentOS and Ubuntu
  hosts: target
  become: yes
  tasks:
    - block:
        - name: Install Telegraf Agent
          apt:
            deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.18.1-1_amd64.deb
        - name: Start Telegraf
          service:
            name: telegraf
            state: started
            enabled: yes
      when: ansible_distribution == "Ubuntu"
- name: Print info
  hosts: target
  become: true
  tasks:
    - name: Show ansible_facts
      debug:
        var: ansible_facts.default_ipv4.address