---
- name: Install Telegraf Linux
  hosts: target
  become: yes
  tasks:
    - name: check distro
      debug:
        var: ansible_distribution
    # Ubuntu
    - block:
        - name: Get influxdata repo key
          ansible.builtin.get_url:
              url: https://repos.influxdata.com/influxdata-archive_compat.key
              dest: /tmp/influxdata-archive_compat.key
        - name: Setup influxdata repo
          ansible.builtin.shell: |
            echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c /tmp/influxdata-archive_compat.key' | sha256sum -c && cat /tmp/influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
            echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
        - name: Install telegraf agent
          ansible.builtin.apt:
            name: telegraf
            state: present
            update_cache: yes
        - name: Copy telegraf config
          ansible.builtin.copy:
            src: /etc/telegraf/telegraf.d/telegraf-custom.conf
            dest: /etc/telegraf/telegraf.d/telegraf-custom.conf
        - name: Start telegraf agent
          ansible.builtin.systemd:
            name: telegraf
            state: started
            enabled: yes
      when: ansible_distribution == "Ubuntu"
    # CentOS
    - block:
        - name: Setup influxdata repo
          ansible.builtin.shell: |
            cat <<EOF | sudo tee /etc/yum.repos.d/influxdb.repo
            [influxdb]
            name = InfluxData Repository - Stable
            baseurl = https://repos.influxdata.com/stable/\$basearch/main
            enabled = 1
            gpgcheck = 1
            gpgkey = https://repos.influxdata.com/influxdata-archive_compat.key
            EOF
        - name: Install telegraf agent
          ansible.builtin.yum:
            name: telegraf
            state: present
            update_cache: true
        - name: Copy telegraf config
          ansible.builtin.copy:
            src: /etc/telegraf/telegraf.d/telegraf-custom.conf
            dest: /etc/telegraf/telegraf.d/telegraf-custom.conf
        - name: Start telegraf agent
          ansible.builtin.systemd:
            name: telegraf
            state: started
            enabled: yes
      when: ansible_distribution == "CentOS"
  # Restart Handler
  handlers:
        - name: Restart Telegraf
          ansible.builtin.systemd:
            name: telegraf
            state: restarted
- name: Print info
  hosts: target
  become: true
  tasks:
    - name: Show ansible_facts:\ Target VMs Private ip
      debug:
        var: ansible_facts.default_ipv4.address
