---
- name: Install Telegraf CentOS and Ubuntu
  hosts: target
  become: yes
  tasks:
    - block:
        - name: Install Telegraf Agent - Ubuntu
          apt:
            deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.18.1-1_amd64.deb
        - name: Copy telegraf config - Ubuntu
          copy:
            src: ./config/telegraf.conf
            dest: /etc/telegraf/telegraf.conf
          notify:
          - Restart Telegraf
        - name: Start Telegraf - Ubuntu
          service:
            name: telegraf
            state: started
            enabled: yes
      when: ansible_distribution == "Ubuntu"
    - block:
        - name: Download Telegraf rpm
          get_url:
            url: https://dl.influxdata.com/telegraf/releases/telegraf-1.18.1-1.x86_64.rpm
            dest: /usr/local/telegraf-1.18.1-1.x86_64.rpm
        - name: Install Telegraf Agent - CentOS
          yum:
            name: /usr/local/telegraf-1.18.1-1.x86_64.rpm
            disable_gpg_check: yes
        - name: Copy telegraf config - Ubuntu
          copy:
            src: ./config/telegraf.conf
            dest: /etc/telegraf/telegraf.conf
          notify:
          - Restart Telegraf
        - name: Start Telegraf - Ubuntu
          service:
            name: telegraf
            state: started
            enabled: yes
      when: ansible_distribution == "CentOS"
  handlers:
        - name: Restart Telegraf
          ansible.builtin.service:
            name: telegraf
            state: restarted
- name: Print info
  hosts: target
  become: true
  tasks:
    - name: Show ansible_facts:\ Target VMs Private ip
      debug:
        var: ansible_facts.default_ipv4.address