---
- name: Apache install CentOS and Ubuntu
  hosts: web
  become: yes
  tasks:
    - block:
        - name: Install Httpd
          yum:
            name: httpd
            state: latest
        - name: Copy index.html
          copy:
            src: index.html
            dest: /var/www/html/
        - name: Start httpd
          service:
            name: httpd
            state: started
            enabled: yes
      when: ansible_distribution == "CentOS"
    - block:
        - name: Install apache2
          apt:
            name: apache2
            state: present
        - name: Copy index.html
          copy:
            src: index.html
            dest: /var/www/html/index.html
        - name: Start apache2
          service:
            name: apache2
            state: started
            enabled: yes
      when: ansible_distribution == "Ubuntu"